# Generated by Django 5.2.3 on 2025-06-13 12:55

import voice.models.answer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image as your answer', null=True, upload_to=voice.models.answer.answer_image_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('select_image', 'Select Image'), ('integer', 'integer'), ('float', 'float'), ('date', 'date'), ('image-upload', 'Image Upload')], default='text', max_length=150, verbose_name='Type of question'),
        ),
    ]
